{% set name = "resp" %}
{% set version = "1.0.0" %}
{% set git_version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cdsgroup/resp/archive/refs/tags/v{{ git_version }}.tar.gz
  sha256: e3bf8a3df69e5b909877df221ce0aa3dd139c176edbcccec0a3e8a738c03a921

  patches:
    # The tagged version upstream did not update the setup.py version to 1.0.0.
    - versions.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - numpy
    - python >={{ python_min }}
    - psi4

test:
  requires:
    - pytest
    - pip
    - python {{ python_min }}
  imports:
    - psi4
    - resp
  commands:
    - pip check
    - python -c "import resp, sys; sys.exit(resp.test())"  # [unix]
    - python -c "import resp;assert resp.__version__ == '{{ version }}', f'{resp.__version__=} differs from recipe=\'{{ version }}\''"

about:
  home: https://github.com/cdsgroup/resp
  dev_url: https://github.com/cdsgroup/resp
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: "A. Alenaizan's restrained electrostatic potential (RESP) plugin to Psi4"

extra:
  recipe-maintainers:
    - loriab
    - hadim
